language: ruby
rvm:
  - 2.0.0
  - 2.1

branches:
  only:
    - v1.0.2

gemfile:
  - Gemfile

matrix:
  include:
    - rvm: 2.0.0
      gemfile: gemfiles/rails40.gemfile

    - rvm: 2.1
      gemfile: gemfiles/rails40.gemfile

    - rvm: 2.0.0
      gemfile: gemfiles/rails41.gemfile

    - rvm: 2.1
      gemfile: gemfiles/rails41.gemfile